// CS subjects: common interview questions (written for this app), grouped by topic, with free study resources.
const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 70);
const g = (key, name, topics, list) => ({ key, name, topics, list });
const yt = q => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;
const gfg = q => `https://www.google.com/search?q=${encodeURIComponent("site:geeksforgeeks.org " + q)}`;

const RAW = {
  dbms: {
    name: "DBMS", long: "Database management systems",
    intro: "Asked in almost every placement interview: keys, normalization, transactions, indexing and SQL queries.",
    resources: [
      ["Read", "Database System Concepts (the standard textbook, slides free)", "https://db-book.com/"],
      ["Watch", "CMU 15-445 Database Systems (free university course)", "https://15445.courses.cs.cmu.edu/"],
      ["Read", "Use The Index, Luke (indexing, free book)", "https://use-the-index-luke.com/"],
      ["Watch", "Gate Smashers DBMS playlist", yt("gate smashers dbms playlist")],
      ["Read", "GeeksforGeeks DBMS tutorial", gfg("DBMS tutorial")],
      ["Interview", "InterviewBit DBMS interview questions", "https://www.interviewbit.com/dbms-interview-questions/"],
      ["Practice", "SQLBolt (interactive SQL lessons)", "https://sqlbolt.com/"],
      ["Practice", "LeetCode Top SQL 50", "https://leetcode.com/studyplan/top-sql-50/"],
    ],
    groups: [
      g("basics", "Basics", ["DBMS Basics"], [
        ["E", "What is a DBMS, and why is it better than storing data in files?"],
        ["E", "What is the difference between DBMS and RDBMS?"],
        ["E", "What are a schema and an instance in a database?"],
        ["M", "What is data independence? Explain logical and physical data independence."],
        ["M", "Explain the three-schema architecture (external, conceptual, internal)."],
        ["E", "What are DDL, DML, DCL and TCL commands? Give examples of each."],
        ["E", "What is the difference between DELETE, TRUNCATE and DROP?"],
        ["M", "What is a view? Can you update data through a view?"],
        ["M", "What are stored procedures and triggers, and when would you use each?"],
        ["M", "What is a cursor in SQL?"],
      ]),
      g("keys", "Keys and constraints", ["Keys"], [
        ["E", "What is a primary key? Can it be NULL?"],
        ["E", "What is the difference between a primary key and a unique key?"],
        ["E", "What is a foreign key, and how does it keep data consistent?"],
        ["M", "Explain super key, candidate key and alternate key with an example."],
        ["E", "What is a composite key?"],
        ["M", "What is referential integrity? What does ON DELETE CASCADE do?"],
      ]),
      g("er", "ER model and design", ["ER Model"], [
        ["E", "What is an ER diagram, and what are its main parts?"],
        ["M", "What is a weak entity? Give an example."],
        ["M", "Explain one-to-one, one-to-many and many-to-many relationships. How do you store many-to-many in tables?"],
        ["H", "What are generalisation, specialisation and aggregation?"],
        ["M", "Design the database tables for a library management system."],
      ]),
      g("normalization", "Normalization", ["Normalization"], [
        ["E", "What is normalization, and why do we need it?"],
        ["M", "What are insertion, update and deletion anomalies?"],
        ["M", "What is a functional dependency?"],
        ["M", "Explain 1NF, 2NF and 3NF with an example."],
        ["H", "What is BCNF, and how is it different from 3NF?"],
        ["M", "What is denormalization, and when is it a good idea?"],
        ["H", "What is 4NF, and what is a multivalued dependency?"],
        ["H", "What is a lossless join decomposition?"],
      ]),
      g("transactions", "Transactions and ACID", ["Transactions and ACID"], [
        ["E", "What is a transaction?"],
        ["E", "Explain the ACID properties using a bank transfer example."],
        ["M", "What are the states of a transaction?"],
        ["E", "What do COMMIT, ROLLBACK and SAVEPOINT do?"],
        ["H", "How does a database recover after a crash? Explain logs and checkpoints."],
        ["H", "What is a schedule, and when is a schedule serializable?"],
      ]),
      g("concurrency", "Concurrency control", ["Concurrency Control"], [
        ["M", "What problems can happen when transactions run at the same time (dirty read, lost update, non-repeatable read, phantom read)?"],
        ["M", "Explain the four isolation levels in SQL."],
        ["H", "What is two-phase locking (2PL)?"],
        ["M", "What is the difference between a shared lock and an exclusive lock?"],
        ["M", "What is the difference between optimistic and pessimistic locking?"],
        ["M", "How can a deadlock happen in a database, and how is it handled?"],
        ["H", "What is MVCC (multi-version concurrency control)?"],
      ]),
      g("indexing", "Indexing", ["Indexing"], [
        ["E", "What is an index, and how does it make queries faster?"],
        ["M", "What is the difference between a clustered and a non-clustered index?"],
        ["H", "Why do databases use B+ trees for indexes?"],
        ["M", "When should you NOT add an index?"],
        ["M", "What is a composite index, and why does the column order matter?"],
        ["H", "What is the difference between a hash index and a B+ tree index?"],
        ["M", "How would you find out why a SQL query is slow?"],
      ]),
      g("sql", "SQL queries", ["SQL Queries"], [
        ["E", "Write a query to find the second highest salary."],
        ["M", "Write a query to find the Nth highest salary."],
        ["E", "Explain INNER, LEFT, RIGHT and FULL joins with an example."],
        ["M", "What is a self join? Give a use case."],
        ["E", "What is the difference between WHERE and HAVING?"],
        ["E", "What is the difference between UNION and UNION ALL?"],
        ["M", "What are window functions? Explain ROW_NUMBER, RANK and DENSE_RANK."],
        ["E", "Write a query to find duplicate rows in a table."],
        ["M", "Write a query to find employees who earn more than their managers."],
        ["M", "What is a correlated subquery?"],
        ["H", "What is a CTE (WITH clause)? When would you use a recursive CTE?"],
      ]),
      g("nosql", "SQL vs NoSQL and scaling", ["Databases", "Sharding", "Replication", "CAP Theorem"], [
        ["M", "SQL vs NoSQL: when would you choose each?"],
        ["M", "What are the types of NoSQL databases? Give an example of each."],
        ["M", "What is database sharding?"],
        ["M", "What is the difference between replication and sharding?"],
        ["M", "Explain the CAP theorem."],
      ]),
    ],
  },
  os: {
    name: "Operating systems", long: "Operating systems",
    intro: "Processes, scheduling, synchronization, deadlocks and memory. Expect both theory and small numericals.",
    resources: [
      ["Read", "Operating Systems: Three Easy Pieces (free book)", "https://pages.cs.wisc.edu/~remzi/OSTEP/"],
      ["Watch", "Gate Smashers operating system playlist", yt("gate smashers operating system playlist")],
      ["Watch", "Neso Academy operating system playlist", yt("neso academy operating system playlist")],
      ["Read", "GeeksforGeeks operating systems tutorial", gfg("operating systems tutorial")],
      ["Interview", "InterviewBit operating system interview questions", "https://www.interviewbit.com/operating-system-interview-questions/"],
    ],
    groups: [
      g("kernel", "OS basics and the kernel", ["Kernel and System Calls"], [
        ["E", "What is an operating system, and what are its main jobs?"],
        ["M", "What is a kernel? Compare monolithic kernels and microkernels."],
        ["E", "What is a system call? Give some examples."],
        ["M", "What is the difference between user mode and kernel mode?"],
        ["M", "What is an interrupt, and how is it handled?"],
        ["M", "What happens when you turn on a computer (the boot process)?"],
        ["E", "What are the types of operating systems (batch, time-sharing, real-time, distributed)?"],
        ["M", "What is a real-time operating system? Compare hard and soft real-time systems."],
      ]),
      g("processes", "Processes and threads", ["Processes and Threads"], [
        ["E", "What is the difference between a process and a program?"],
        ["E", "What is the difference between a process and a thread?"],
        ["E", "What are the states of a process?"],
        ["M", "What is a PCB (process control block)?"],
        ["M", "What is a context switch, and why is it costly?"],
        ["M", "What does fork() do? How many processes do three fork() calls create?"],
        ["M", "What are zombie and orphan processes?"],
        ["H", "What is the difference between user-level threads and kernel-level threads?"],
        ["M", "What is inter-process communication (IPC)? Name some ways to do it."],
        ["M", "Compare multiprogramming, multitasking, multithreading and multiprocessing."],
      ]),
      g("scheduling", "CPU scheduling", ["CPU Scheduling"], [
        ["E", "What is CPU scheduling, and why is it needed?"],
        ["M", "Explain FCFS, SJF, SRTF, priority and Round Robin scheduling."],
        ["E", "What is the difference between preemptive and non-preemptive scheduling?"],
        ["E", "Define arrival, burst, completion, turnaround, waiting and response time."],
        ["M", "What is the convoy effect?"],
        ["M", "What is starvation, and how does aging fix it?"],
        ["M", "How does the size of the time quantum affect Round Robin?"],
        ["H", "What is multilevel feedback queue scheduling?"],
      ]),
      g("sync", "Process synchronization", ["Process Synchronization", "Concurrency"], [
        ["E", "What is a race condition?"],
        ["M", "What is a critical section, and what are the three requirements for a correct solution?"],
        ["M", "What is the difference between a mutex and a semaphore?"],
        ["M", "What is the difference between a binary semaphore and a counting semaphore?"],
        ["H", "Explain the producer-consumer problem and solve it using semaphores."],
        ["H", "Explain the readers-writers problem."],
        ["H", "Explain the dining philosophers problem. How do you avoid deadlock in it?"],
        ["M", "What is a monitor?"],
        ["M", "What is a spinlock? When is busy waiting acceptable?"],
        ["H", "What is Peterson's solution?"],
      ]),
      g("deadlock", "Deadlocks", ["Deadlock"], [
        ["E", "What is a deadlock? Give a real-life example."],
        ["E", "What are the four necessary conditions for a deadlock?"],
        ["M", "How can deadlocks be prevented?"],
        ["H", "Explain the Banker's algorithm with an example."],
        ["M", "What is a resource allocation graph?"],
        ["M", "What is the difference between deadlock, starvation and livelock?"],
        ["M", "How is a deadlock detected, and how does the system recover?"],
      ]),
      g("memory", "Memory management", ["Memory Management"], [
        ["E", "What is memory management, and why is it needed?"],
        ["E", "What is the difference between a logical address and a physical address?"],
        ["M", "What is paging?"],
        ["M", "What is segmentation, and how is it different from paging?"],
        ["E", "What is the difference between internal and external fragmentation?"],
        ["M", "What is a TLB, and why does it speed up paging?"],
        ["E", "What are first fit, best fit and worst fit?"],
        ["M", "What is compaction?"],
        ["E", "What is the difference between stack and heap memory?"],
      ]),
      g("virtual", "Virtual memory", ["Virtual Memory"], [
        ["E", "What is virtual memory?"],
        ["M", "What is demand paging?"],
        ["M", "What is a page fault, and what happens during one?"],
        ["M", "Explain FIFO, LRU and Optimal page replacement with an example."],
        ["H", "What is Belady's anomaly?"],
        ["M", "What is thrashing, and how can it be prevented?"],
        ["H", "What is the working set model?"],
        ["H", "What is copy-on-write?"],
      ]),
      g("files", "File systems and disks", ["File Systems and Disks"], [
        ["E", "What is a file system?"],
        ["M", "What is an inode?"],
        ["M", "Explain contiguous, linked and indexed file allocation."],
        ["M", "Explain FCFS, SSTF, SCAN, C-SCAN and LOOK disk scheduling."],
        ["M", "What is RAID? Explain RAID 0, 1 and 5."],
        ["M", "What is the difference between a hard link and a soft link?"],
        ["M", "What is the difference between a buffer and a cache?"],
      ]),
    ],
  },
  cn: {
    name: "Computer networks", long: "Computer networks",
    intro: "OSI layers, TCP/UDP, HTTP, DNS and \"what happens when you type a URL\" come up again and again.",
    resources: [
      ["Read", "High Performance Browser Networking (free book)", "https://hpbn.co/"],
      ["Read", "Cloudflare Learning Center (DNS, TCP, HTTPS, DDoS explained)", "https://www.cloudflare.com/learning/"],
      ["Read", "MDN: An overview of HTTP", "https://developer.mozilla.org/en-US/docs/Web/HTTP"],
      ["Read", "Beej's Guide to Network Programming (sockets)", "https://beej.us/guide/bgnet/"],
      ["Watch", "Gate Smashers computer networks playlist", yt("gate smashers computer networks playlist")],
      ["Watch", "Neso Academy computer networks playlist", yt("neso academy computer networks playlist")],
      ["Read", "GeeksforGeeks computer network tutorials", gfg("computer network tutorial")],
      ["Interview", "InterviewBit networking interview questions", "https://www.interviewbit.com/networking-interview-questions/"],
    ],
    groups: [
      g("models", "Network models and basics", ["OSI and TCP/IP Models"], [
        ["E", "Explain the 7 layers of the OSI model."],
        ["E", "What is the difference between the OSI and TCP/IP models?"],
        ["M", "What is encapsulation in networking?"],
        ["E", "At which layer do hubs, switches and routers work?"],
        ["E", "What are LAN, MAN, WAN and PAN?"],
        ["E", "What is network topology? Explain bus, star, ring and mesh."],
        ["E", "What is the difference between bandwidth, latency and throughput?"],
      ]),
      g("transport", "TCP and UDP", ["TCP and UDP"], [
        ["E", "What is the difference between TCP and UDP?"],
        ["E", "Explain the TCP 3-way handshake."],
        ["M", "How is a TCP connection closed (the 4-way handshake)?"],
        ["E", "What is a port, and what is a socket?"],
        ["E", "Name the common port numbers for HTTP, HTTPS, SSH, DNS, FTP and SMTP."],
        ["M", "Why does DNS mostly use UDP? When does it use TCP?"],
        ["M", "Why do video calls and online games prefer UDP?"],
        ["H", "What is QUIC?"],
      ]),
      g("http", "HTTP, HTTPS and the web", ["HTTP and HTTPS"], [
        ["M", "What happens when you type google.com into your browser and press Enter?"],
        ["E", "What is the difference between HTTP and HTTPS?"],
        ["H", "How does the TLS handshake work?"],
        ["E", "Explain the HTTP methods GET, POST, PUT, PATCH and DELETE."],
        ["E", "Explain the HTTP status codes 200, 201, 301, 302, 400, 401, 403, 404, 500 and 503."],
        ["M", "What is the difference between cookies, sessions and local storage?"],
        ["M", "What is REST? What makes an API RESTful?"],
        ["H", "What changed between HTTP/1.1, HTTP/2 and HTTP/3?"],
        ["M", "What is CORS?"],
        ["M", "What are WebSockets, and how are they different from HTTP polling?"],
        ["M", "What is the difference between a proxy and a reverse proxy?"],
        ["E", "What is a CDN?"],
      ]),
      g("dns", "DNS", ["DNS"], [
        ["E", "What is DNS, and why do we need it?"],
        ["M", "Explain how DNS resolution works step by step."],
        ["M", "What are the DNS record types A, AAAA, CNAME, MX, NS and TXT?"],
        ["M", "What is the difference between recursive and iterative DNS queries?"],
        ["M", "What are DNS caching and TTL?"],
      ]),
      g("ip", "IP addressing and subnetting", ["IP Addressing and Subnetting"], [
        ["E", "What is an IP address? Compare IPv4 and IPv6."],
        ["E", "What are the IP address classes A, B, C, D and E?"],
        ["E", "What is a subnet mask?"],
        ["M", "What is subnetting, and why is it used? Work through an example with a /26 network."],
        ["M", "What is CIDR notation?"],
        ["E", "What is the difference between public and private IP addresses?"],
        ["M", "What is NAT?"],
        ["E", "What is the loopback address 127.0.0.1?"],
      ]),
      g("routing", "Routing and switching", ["Routing and Switching"], [
        ["E", "What is the difference between a hub, a switch and a router?"],
        ["E", "What is the difference between a MAC address and an IP address?"],
        ["M", "What is ARP?"],
        ["M", "What is DHCP? Explain the DORA process."],
        ["E", "What is a default gateway?"],
        ["M", "What is routing? Compare static and dynamic routing."],
        ["H", "What is the difference between distance vector and link state routing (RIP vs OSPF)?"],
        ["H", "What is BGP?"],
        ["M", "What is a VLAN?"],
        ["E", "What is the difference between unicast, multicast and broadcast?"],
      ]),
      g("flow", "Flow, congestion and error control", ["Flow and Congestion Control"], [
        ["M", "What is the difference between flow control and congestion control?"],
        ["M", "Explain the sliding window protocol."],
        ["H", "Compare Stop-and-Wait, Go-Back-N and Selective Repeat."],
        ["H", "How does TCP congestion control work (slow start and congestion avoidance)?"],
        ["M", "What is a checksum, and what is CRC?"],
        ["M", "What is the difference between error detection and error correction?"],
      ]),
      g("security", "Network security", ["Network Security"], [
        ["E", "What is the difference between symmetric and asymmetric encryption?"],
        ["M", "What are digital certificates and certificate authorities?"],
        ["E", "What is a firewall?"],
        ["E", "What is a VPN?"],
        ["M", "What is a DDoS attack, and how can you defend against it?"],
        ["M", "What is a man-in-the-middle attack?"],
        ["M", "What are SQL injection and XSS, and how do you prevent them?"],
        ["M", "What is the difference between hashing, encryption and encoding?"],
        ["E", "What is SSH?"],
      ]),
    ],
  },
  oops: {
    name: "OOPs", long: "Object-oriented programming",
    intro: "The four pillars, overloading vs overriding, abstract classes vs interfaces, SOLID and a few design patterns.",
    resources: [
      ["Read", "Oracle Java tutorial: object-oriented programming concepts", "https://docs.oracle.com/javase/tutorial/java/concepts/"],
      ["Read", "LearnCpp (C++ classes, inheritance, virtual functions)", "https://www.learncpp.com/"],
      ["Read", "Python tutorial: classes", "https://docs.python.org/3/tutorial/classes.html"],
      ["Read", "Refactoring Guru: design patterns explained with pictures", "https://refactoring.guru/design-patterns"],
      ["Watch", "OOPs concepts for interviews", yt("oops concepts interview questions")],
      ["Read", "GeeksforGeeks OOPs concepts", gfg("OOPs concepts")],
      ["Interview", "InterviewBit OOPs interview questions", "https://www.interviewbit.com/oops-interview-questions/"],
    ],
    groups: [
      g("basics", "OOP basics", ["OOP"], [
        ["E", "What is object-oriented programming, and why do we use it?"],
        ["E", "What are the four pillars of OOP?"],
        ["E", "What is the difference between procedural and object-oriented programming?"],
        ["E", "What is an exception? Compare checked and unchecked exceptions."],
        ["M", "What are generics (Java) or templates (C++)?"],
      ]),
      g("classes", "Classes and objects", ["Classes and Objects"], [
        ["E", "What is the difference between a class and an object?"],
        ["E", "What is a constructor, and what types of constructors are there?"],
        ["M", "What is a copy constructor, and when is it called?"],
        ["M", "Can a constructor be private? When is that useful?"],
        ["E", "What does the this keyword mean?"],
        ["E", "What are static variables and static methods?"],
        ["M", "What is a friend function in C++?"],
        ["M", "What is an inline function?"],
      ]),
      g("encapsulation", "Encapsulation", ["Encapsulation"], [
        ["E", "What is encapsulation? Give a real example."],
        ["E", "Explain the access modifiers private, protected, public and default."],
        ["E", "Why use getters and setters instead of public fields?"],
        ["M", "What is the difference between encapsulation and abstraction?"],
      ]),
      g("inheritance", "Inheritance", ["Inheritance"], [
        ["E", "What is inheritance, and what are its types?"],
        ["M", "Why doesn't Java allow multiple inheritance of classes? What is the diamond problem?"],
        ["H", "How does C++ solve the diamond problem with virtual inheritance?"],
        ["E", "What does the super keyword do?"],
        ["M", "Composition vs inheritance: when should you prefer composition?"],
        ["E", "What is the difference between an is-a and a has-a relationship?"],
        ["M", "What is the difference between association, aggregation and composition?"],
      ]),
      g("polymorphism", "Polymorphism", ["Polymorphism"], [
        ["E", "What is polymorphism?"],
        ["E", "What is the difference between method overloading and method overriding?"],
        ["M", "What is the difference between compile-time and runtime polymorphism?"],
        ["H", "What is a virtual function, and how does a vtable work?"],
        ["M", "Can you override a static method? Can you overload main()?"],
        ["M", "What is operator overloading?"],
        ["M", "What is dynamic method dispatch?"],
      ]),
      g("abstraction", "Abstraction and interfaces", ["Abstraction and Interfaces"], [
        ["E", "What is abstraction?"],
        ["E", "What is the difference between an abstract class and an interface?"],
        ["M", "What is a pure virtual function?"],
        ["M", "Can an abstract class have a constructor?"],
        ["M", "What are default methods in Java interfaces?"],
        ["H", "What is a marker interface?"],
      ]),
      g("memory", "Memory and object lifecycle", ["Memory and Object Lifecycle"], [
        ["E", "What is a destructor? Does Java have one?"],
        ["M", "How does garbage collection work in Java?"],
        ["M", "What is the difference between a shallow copy and a deep copy?"],
        ["E", "Where are objects stored: stack or heap?"],
        ["M", "What is a memory leak, and how can it happen in Java or C++?"],
        ["H", "What are smart pointers in C++ (unique_ptr and shared_ptr)?"],
        ["E", "What is the difference between final, finally and finalize in Java?"],
      ]),
      g("solid", "SOLID and good design", ["SOLID"], [
        ["M", "Explain the SOLID principles with examples."],
        ["E", "What is the single responsibility principle?"],
        ["M", "What is dependency injection?"],
        ["H", "What is the Liskov substitution principle? Show an example that breaks it."],
        ["M", "What are coupling and cohesion?"],
      ]),
      g("patterns", "Design patterns", ["Singleton", "Factory", "Strategy", "Observer", "Decorator"], [
        ["E", "What is a design pattern? Name the three categories of patterns."],
        ["M", "Write a thread-safe Singleton class."],
        ["M", "Explain the Factory pattern with an example."],
        ["M", "Explain the Strategy pattern with an example."],
        ["M", "Explain the Observer pattern with an example."],
        ["H", "Explain the Decorator pattern with an example."],
      ]),
    ],
  },
};

export const CS_SUBJECTS = Object.entries(RAW).map(([id, s]) => ({
  id, name: s.name, long: s.long, intro: s.intro,
  resources: s.resources.map(([kind, name, url]) => ({ kind, name, url })),
  groups: s.groups.map(gr => ({
    id: `${id}-${gr.key}`, name: gr.name, topics: gr.topics,
    items: gr.list.map(([level, text]) => ({
      id: `cs:${id}:${slug(text)}`, kind: "cs", subject: id, subjectName: s.long, level, title: text, concepts: gr.topics,
    })),
  })),
}));
export const CS_BY_ID = Object.fromEntries(CS_SUBJECTS.flatMap(s => s.groups.flatMap(gr => gr.items.map(i => [i.id, i]))));
export const isCS = id => typeof id === "string" && id.startsWith("cs:");
export const csStudyLinks = item => [
  { name: "Read on GeeksforGeeks", url: gfg(item.title) },
  { name: "Watch on YouTube", url: yt(`${item.title} ${item.subjectName}`) },
];
