// Hand-written pattern for every question on the DSA path (scripts/sequence.mjs).
// Format:  "leetcode-slug": "main-pattern+second-pattern: why it applies here (the cue to look for)"
// Pattern keys are defined in lib/patterns.js. The first key is the main pattern; `npm test` checks every key exists
// and that every path question has an entry.
export const PATH_PATTERNS = {
  // ---- Programming basics ----
  "fizz-buzz": "simulation: Loop 1..n and check the divisible-by-15 case before 3 and 5.",
  "running-sum-of-1d-array": "prefix-sum: Each output is the sum so far, which is exactly a prefix sum.",
  "richest-customer-wealth": "simulation: Sum each row, keep the maximum. Nothing clever needed.",
  "number-of-steps-to-reduce-a-number-to-zero": "simulation+bit-manipulation: Even means divide by 2, odd means subtract 1. In bits, that is shift or clear the lowest bit.",
  "convert-the-temperature": "math-digits: Apply the given formulas directly.",
  "smallest-even-multiple": "number-theory: The answer is lcm(2, n), so n if n is even and 2n if odd.",
  "count-odd-numbers-in-an-interval-range": "math-digits: Count with a formula instead of looping the range.",
  "subtract-the-product-and-sum-of-digits-of-an-integer": "math-digits: Peel digits with % 10 and / 10.",
  "find-numbers-with-even-number-of-digits": "math-digits: Count digits with a loop or by converting to a string.",
  "count-the-digits-that-divide-a-number": "math-digits: Peel each digit and test n % digit.",
  "difference-between-element-sum-and-digit-sum-of-an-array": "math-digits: One pass for the element sum, digit peeling for the digit sum.",
  "sign-of-the-product-of-an-array": "simulation: You never need the product. Return 0 on a zero and count the negatives.",
  "average-salary-excluding-the-minimum-and-maximum-salary": "simulation: Track min, max and total in one pass. No sort needed.",
  "palindrome-number": "math-digits+two-pointers-opposite: Reverse the second half of the digits and compare, or compare the two ends.",
  "reverse-integer": "math-digits: Build the reverse with % 10 and * 10, and check overflow before the multiply.",
  "add-digits": "math-digits: Repeated digit sum has a closed form (digital root) using % 9.",
  "jewels-and-stones": "hash-lookup: Put the jewel letters in a set, then test each stone.",
  "number-of-good-pairs": "frequency-count: A value seen c times gives c·(c−1)/2 pairs. Count as you go.",
  "defanging-an-ip-address": "simulation: Replace each dot while building the new string.",
  "to-lower-case": "simulation: Map each letter by its character code.",
  "length-of-last-word": "two-pointers-opposite: Scan from the end, skip spaces, then count letters.",
  "maximum-number-of-words-found-in-sentences": "simulation: Count spaces + 1 per sentence and keep the maximum.",

  // ---- Time complexity and maths ----
  "power-of-two": "bit-manipulation: A power of two has exactly one set bit, so n > 0 and n & (n−1) == 0.",
  "power-of-three": "math-digits: Divide by 3 while divisible. Or test whether n divides the largest power of 3 that fits in an int.",
  "happy-number": "fast-slow+hash-lookup: The digit-square sequence either reaches 1 or loops. Detect the loop with a set or fast/slow.",
  "ugly-number": "math-digits: Divide out 2, 3 and 5 repeatedly, and check whether 1 is left.",
  "self-dividing-numbers": "math-digits: For each number, check every digit divides it. Reject digit 0.",
  "perfect-number": "number-theory: Sum divisors up to √n, adding both d and n/d.",
  "count-of-matches-in-tournament": "math-digits: Every match removes exactly one team, so the answer is n − 1.",
  "excel-sheet-column-number": "math-digits: Base-26 conversion: result = result · 26 + letter value.",
  "excel-sheet-column-title": "math-digits: Base-26 but 1-indexed, so subtract 1 before each % 26.",
  "find-greatest-common-divisor-of-array": "number-theory: Euclid's gcd on the min and max.",
  "greatest-common-divisor-of-strings": "number-theory: If a+b == b+a a common root exists, and its length is gcd(len a, len b).",
  "plus-one": "simulation: Add from the right with a carry. All 9s means a new leading 1.",
  "add-binary": "simulation: Two pointers from the right, adding with a carry, like school addition.",
  "factorial-trailing-zeroes": "number-theory: Trailing zeroes are pairs of 2 and 5, so count factors of 5: n/5 + n/25 + …",
  "count-primes": "number-theory: Sieve of Eratosthenes. Start crossing off at p·p.",

  // ---- Arrays ----
  "concatenation-of-array": "simulation: Copy the array twice with index math i and i + n.",
  "build-array-from-permutation": "simulation: Direct index lookup ans[i] = nums[nums[i]].",
  "shuffle-the-array": "two-pointers-same: Interleave the first half and second half with two indices.",
  "kids-with-the-greatest-number-of-candies": "simulation: Find the max once, then compare each value + extra with it.",
  "find-the-highest-altitude": "prefix-sum: Altitudes are the running sum of the gains.",
  "max-consecutive-ones": "sliding-window-variable: Count the current run of 1s, reset on 0, keep the best.",
  "third-maximum-number": "simulation: Keep the top three distinct values in one pass.",
  "check-if-array-is-sorted-and-rotated": "simulation: A sorted rotated array has at most one place where a value drops (check circularly).",
  "missing-number": "xor-trick+math-digits: XOR all indices and values, or use n(n+1)/2 minus the sum. Values are 0..n.",
  "single-number": "xor-trick: Everything appears twice except one, so pairs cancel under XOR.",
  "majority-element": "boyer-moore: Appears more than n/2 times. Boyer-Moore voting gives O(1) space.",
  "find-all-numbers-disappeared-in-an-array": "index-marking: Values are 1..n. Flip the sign at index v−1 and report the still-positive slots.",
  "pascals-triangle": "dp-linear: Each cell is the sum of the two cells above it.",
  "transpose-matrix": "matrix-traversal: Swap rows and columns: out[c][r] = in[r][c].",
  "matrix-diagonal-sum": "matrix-traversal: Walk i with [i][i] and [i][n−1−i], and don't double count the centre.",
  "best-time-to-buy-and-sell-stock": "kadane: Track the lowest price so far and the best profit selling today (same idea as Kadane).",
  "best-time-to-buy-and-sell-stock-ii": "greedy: Many transactions allowed, so add up every positive day-to-day rise.",
  "rotate-array": "two-pointers-same: Reverse everything, then reverse the first k and the last n−k.",
  "maximum-subarray": "kadane: Best subarray ending here is max(x, best_here + x).",
  "product-of-array-except-self": "prefix-sum: Product of everything left times product of everything right (prefix and suffix products).",
  "majority-element-ii": "boyer-moore: More than n/3 means at most two candidates. Keep two counters and verify.",
  "next-permutation": "two-pointers-same: Find the rightmost dip, swap with the next larger value on its right, reverse the tail.",
  "set-matrix-zeroes": "matrix-traversal: Use the first row and column as flags to stay O(1) space.",
  "rotate-image": "matrix-traversal: Transpose, then reverse each row.",
  "spiral-matrix": "matrix-traversal: Four shrinking borders (top, bottom, left, right) or direction turns.",

  // ---- Strings ----
  "reverse-string": "two-pointers-opposite: Swap from both ends toward the middle.",
  "valid-palindrome": "two-pointers-opposite: Skip non-alphanumeric characters from both ends and compare.",
  "is-subsequence": "two-pointers-same: One pointer through t, the other advances in s only on a match.",
  "longest-common-prefix": "simulation+sort-then-scan: Compare column by column, or just compare the smallest and largest strings.",
  "find-the-index-of-the-first-occurrence-in-a-string": "string-matching: Brute force is fine here; KMP gives O(n + m).",
  "largest-odd-number-in-string": "greedy: Trim from the right until the last digit is odd.",
  "remove-outermost-parentheses": "stack-matching: Track the depth counter instead of a real stack.",
  "maximum-nesting-depth-of-the-parentheses": "stack-matching: The answer is the maximum depth counter.",
  "rotate-string": "string-matching: B is a rotation of A exactly when B appears in A + A (same length).",
  "roman-to-integer": "hash-lookup: Map symbol → value. If a smaller value precedes a bigger one, subtract it.",
  "isomorphic-strings": "hash-lookup: Two maps (s→t and t→s), or compare first-seen index. The mapping must be one-to-one.",
  "reverse-words-in-a-string": "two-pointers-opposite: Split on spaces and reverse, or reverse the whole string and then each word.",
  "integer-to-roman": "greedy: Take the largest symbol value that fits, over a table that includes 4, 9, 40, 90, …",
  "count-and-say": "simulation: Build the next term by run-length encoding the previous one.",
  "string-compression": "two-pointers-same: A read pointer scans runs, a write pointer writes the letter and the count in place.",
  "zigzag-conversion": "simulation: Walk the rows down and up with a direction flag, appending to each row.",
  "string-to-integer-atoi": "simulation: Skip spaces, read the sign, read digits, clamp on overflow.",
  "longest-palindromic-substring": "palindrome-expand: Expand around each of the 2n−1 centres.",
  "sum-of-beauty-of-all-substrings": "frequency-count: For every start, extend the end and maintain a 26-count.",

  // ---- Hashing ----
  "two-sum": "hash-lookup: Need a pair that reaches a target, so store seen values and look up target − x.",
  "contains-duplicate": "hash-lookup: A set of seen values answers it in one pass.",
  "valid-anagram": "frequency-count: Equal letter counts means anagram.",
  "first-unique-character-in-a-string": "frequency-count: First pass counts, second pass finds the first letter with count 1.",
  "ransom-note": "frequency-count: Count the magazine's letters and spend them on the note.",
  "word-pattern": "hash-lookup: Same bijection check as isomorphic strings, between pattern letters and words.",
  "intersection-of-two-arrays": "hash-lookup: Put one array in a set and collect matches from the other.",
  "intersection-of-two-arrays-ii": "frequency-count: Count one array, then consume counts while scanning the other (duplicates matter).",
  "contains-duplicate-ii": "sliding-window-fixed+hash-lookup: Keep a set of the last k values, or a map value → last index.",
  "longest-palindrome": "frequency-count: Every pair of letters can be used, plus one odd leftover as the centre.",
  "group-anagrams": "frequency-count: Use the sorted word (or the 26-count) as the map key.",
  "sort-characters-by-frequency": "frequency-count+heap-topk: Count letters, then order by count (sort, heap, or bucket by frequency).",
  "top-k-frequent-elements": "heap-topk+frequency-count: Count with a map, then keep the top k with a heap or bucket sort.",
  "valid-sudoku": "hash-lookup: Sets for each row, column and 3×3 box. Box index is (r/3)*3 + c/3.",
  "longest-consecutive-sequence": "hash-lookup: Put all numbers in a set and start counting only from numbers with no predecessor.",
  "4sum-ii": "hash-lookup: Split into two halves: store all a+b sums in a map, then look up −(c+d).",
  "brick-wall": "hash-lookup+prefix-sum: Count how often each edge position occurs. Fewest bricks cut = rows − the most common edge.",
  "encode-and-decode-tinyurl": "design-ds+hash-lookup: Two maps (id → url, url → id) and a counter or random key.",

  // ---- Sorting ----
  "sort-an-array": "recursion-divide: Implement merge sort or heap sort yourself (no built-in sort).",
  "squares-of-a-sorted-array": "two-pointers-opposite: The largest square is at one of the two ends. Fill the answer from the back.",
  "sort-array-by-parity": "two-pointers-same: Partition with two pointers, swapping evens to the front.",
  "relative-sort-array": "frequency-count: Count values, then emit them in the order of arr2, then the rest sorted.",
  "merge-sorted-array": "two-pointers-same: Merge from the back so nothing is overwritten.",
  "minimum-absolute-difference": "sort-then-scan: After sorting, the smallest differences are between neighbours.",
  "maximum-product-of-three-numbers": "sort-then-scan: Max of (three biggest) or (two smallest negatives × biggest).",
  "sort-colors": "two-pointers-same: Dutch national flag with low, mid and high pointers.",
  "h-index": "frequency-count+sort-then-scan: Sort descending, or counting-sort the citations and walk down.",
  "largest-number": "sort-then-scan+greedy: Sort with a custom comparator: a before b if a+b > b+a as strings.",

  // ---- Recursion ----
  "fibonacci-number": "dp-linear+recursion-divide: Recurrence f(n) = f(n−1) + f(n−2). Memoise or keep two variables.",
  "n-th-tribonacci-number": "dp-linear: Same as Fibonacci but with three previous values.",
  "powx-n": "recursion-divide: Fast power: halve the exponent, square, multiply once more if odd. Handle negative n.",
  "count-good-numbers": "recursion-divide+combinatorics-math: Independent choices per position (5 even, 4 prime), so use fast power under the modulus.",
  "k-th-symbol-in-grammar": "recursion-divide: Row n is row n−1 with each bit expanded, so recurse on the parent index (k+1)/2.",
  "find-the-winner-of-the-circular-game": "simulation+recursion-divide: Simulate with a queue, or use the Josephus recurrence.",
  "sum-of-all-subset-xor-totals": "backtracking-subsets: Include or skip each element and add the XOR at the leaves (or use the OR-of-all × 2^(n−1) shortcut).",
  "different-ways-to-add-parentheses": "recursion-divide: Split at each operator, solve both sides, combine every pair of results.",

  // ---- Two pointers ----
  "move-zeroes": "two-pointers-same: A write pointer for the next non-zero, then fill the rest with zeroes.",
  "remove-element": "two-pointers-same: Copy the elements you keep forward.",
  "remove-duplicates-from-sorted-array": "two-pointers-same: Sorted, so a duplicate equals the last kept value.",
  "backspace-string-compare": "two-pointers-opposite+stack-matching: Walk both strings from the back counting backspaces, for O(1) space.",
  "valid-palindrome-ii": "two-pointers-opposite: On the first mismatch, try skipping the left or the right character, then check the rest.",
  "remove-duplicates-from-sorted-array-ii": "two-pointers-same: Keep a value if it differs from the one two slots behind the write pointer.",
  "two-sum-ii-input-array-is-sorted": "two-pointers-opposite: Sorted pair sum: too small moves left up, too big moves right down.",
  "3sum": "two-pointers-opposite+sort-then-scan: Sort, fix one number, run the two-pointer pair search, skip duplicates.",
  "3sum-closest": "two-pointers-opposite+sort-then-scan: Same as 3Sum, tracking the closest sum.",
  "container-with-most-water": "two-pointers-opposite+greedy: Move the shorter wall inward because that is the only way the area can grow.",
  "boats-to-save-people": "two-pointers-opposite+greedy: Sort. Pair the heaviest with the lightest if they fit, else the heaviest goes alone.",
  "4sum": "two-pointers-opposite+sort-then-scan: Sort, fix two numbers, then two pointers. Skip duplicates at every level.",
  "trapping-rain-water": "two-pointers-opposite+monotonic-stack: Water at i = min(maxLeft, maxRight) − height. Two pointers keep both maxima in O(1) space.",

  // ---- Prefix sum ----
  "find-pivot-index": "prefix-sum: Left sum equals total − left − current.",
  "range-sum-query-immutable": "prefix-sum+design-ds: Many range queries on a fixed array. Precompute prefixes.",
  "range-sum-query-2d-immutable": "prefix-sum: 2D prefix sums with inclusion-exclusion for any rectangle.",
  "product-of-the-last-k-numbers": "prefix-sum+design-ds: Store prefix products (reset on zero), then divide.",
  "subarray-sum-equals-k": "prefix-hash: Count earlier prefixes equal to current − k. Negatives are allowed, so no window.",
  "binary-subarrays-with-sum": "prefix-hash+sliding-window-variable: Prefix + map, or atMost(k) − atMost(k−1).",
  "count-number-of-nice-subarrays": "prefix-hash+sliding-window-variable: Turn odd numbers into 1 and evens into 0, then it is subarray-sum = k.",
  "continuous-subarray-sum": "prefix-hash: Store prefix % k with its first index. Two equal remainders at distance ≥ 2 give a multiple of k.",
  "subarray-sums-divisible-by-k": "prefix-hash: Count pairs of prefixes with equal remainders mod k (fix negatives).",
  "contiguous-array": "prefix-hash: Treat 0 as −1. The longest subarray with sum 0 is first-seen-index distance.",

  // ---- Sliding window ----
  "maximum-average-subarray-i": "sliding-window-fixed: Window of size k: add the new element, subtract the old one.",
  "longest-substring-without-repeating-characters": "sliding-window-variable: Expand right, shrink left while a duplicate is in the window.",
  "maximum-points-you-can-obtain-from-cards": "sliding-window-fixed: Taking k from the ends = leaving a window of n − k in the middle with the minimum sum.",
  "longest-repeating-character-replacement": "sliding-window-variable: Valid when window size − most frequent letter ≤ k.",
  "permutation-in-string": "sliding-window-fixed+frequency-count: Window of len(s1), compare 26-counts.",
  "find-all-anagrams-in-a-string": "sliding-window-fixed+frequency-count: Slide a window of len(p) and compare counts.",
  "max-consecutive-ones-iii": "sliding-window-variable: Longest window containing at most k zeroes.",
  "fruit-into-baskets": "sliding-window-variable: Longest window with at most 2 distinct values.",
  "minimum-size-subarray-sum": "sliding-window-variable: Positive numbers. Shrink while the sum is still ≥ target to get the shortest window.",
  "number-of-substrings-containing-all-three-characters": "sliding-window-variable: For each right end, count how many valid left starts exist once all three letters are inside.",
  "minimum-window-substring": "sliding-window-variable+frequency-count: Expand until all needed letters are covered, then shrink to the smallest.",
  "sliding-window-maximum": "monotonic-deque: Keep indices with decreasing values. The front is the window max.",
  "subarrays-with-k-different-integers": "sliding-window-variable: Exactly k = atMost(k) − atMost(k−1).",

  // ---- Binary search ----
  "binary-search": "binary-search-index: The textbook form.",
  "search-insert-position": "binary-search-index: Lower bound: the first index with value ≥ target.",
  "sqrtx": "binary-search-answer: Search the answer x in [0, n] for the largest x with x·x ≤ n.",
  "guess-number-higher-or-lower": "binary-search-index: The API tells you which half to keep.",
  "first-bad-version": "binary-search-answer: Monotonic good...bad. Find the first bad.",
  "find-first-and-last-position-of-element-in-sorted-array": "binary-search-index: Two binary searches: lower bound and upper bound.",
  "search-in-rotated-sorted-array": "binary-search-index: One half is always sorted. Decide whether the target lies in it.",
  "search-in-rotated-sorted-array-ii": "binary-search-index: Same, but duplicates: when lo, mid, hi are equal shrink both ends.",
  "find-minimum-in-rotated-sorted-array": "binary-search-index: Compare mid with hi to know which side holds the drop.",
  "find-peak-element": "binary-search-index: Follow the slope: if a[mid] < a[mid+1] a peak lies to the right.",
  "single-element-in-a-sorted-array": "binary-search-index: Before the single element pairs start at even indices, after it at odd ones.",
  "search-a-2d-matrix": "binary-search-index: Treat the matrix as one sorted array of length rows × cols.",
  "search-a-2d-matrix-ii": "two-pointers-opposite: Start at top-right. Too big, go left. Too small, go down.",
  "find-k-closest-elements": "binary-search-index+two-pointers-opposite: Binary search the left edge of the window of k.",
  "kth-missing-positive-number": "binary-search-index: missing(i) = a[i] − (i+1) is non-decreasing, so binary search on it.",
  "koko-eating-bananas": "binary-search-answer: Search the speed. feasible(speed) = hours needed ≤ h.",
  "capacity-to-ship-packages-within-d-days": "binary-search-answer: Search the capacity between max weight and total, with a greedy day count.",
  "minimum-number-of-days-to-make-m-bouquets": "binary-search-answer: Search the day. Feasible if you can form m bouquets of k adjacent flowers.",
  "find-the-smallest-divisor-given-a-threshold": "binary-search-answer: Search the divisor. Sum of ceilings must be ≤ threshold.",
  "time-based-key-value-store": "design-time-versioned: Per key keep (timestamp, value) in order and binary search for the floor.",
  "split-array-largest-sum": "binary-search-answer+greedy: Minimise the largest part: search it, check feasibility with a greedy split.",
  "median-of-two-sorted-arrays": "binary-search-index: Binary search the partition of the smaller array so left halves ≤ right halves.",

  // ---- Linked list ----
  "reverse-linked-list": "linked-list-pointer: prev / curr / next rewiring, one node at a time.",
  "merge-two-sorted-lists": "linked-list-pointer: Dummy head, then repeatedly attach the smaller node.",
  "middle-of-the-linked-list": "fast-slow: When fast reaches the end, slow is in the middle.",
  "linked-list-cycle": "fast-slow: Fast and slow meet if there is a cycle.",
  "remove-linked-list-elements": "linked-list-pointer: A dummy head removes the special case for deleting the first node.",
  "delete-node-in-a-linked-list": "linked-list-pointer: You only have the node itself, so copy the next value into it and skip the next node.",
  "palindrome-linked-list": "fast-slow+linked-list-pointer: Find the middle, reverse the second half, compare.",
  "intersection-of-two-linked-lists": "two-pointers-same: Walk A then B and B then A. Both pointers travel the same distance and meet at the intersection.",
  "remove-nth-node-from-end-of-list": "linked-list-pointer+fast-slow: Move the lead pointer n steps ahead, then move both. Use a dummy head.",
  "odd-even-linked-list": "linked-list-pointer: Build the odd chain and the even chain, then join them.",
  "add-two-numbers": "linked-list-pointer+math-digits: Add digit by digit with a carry, using a dummy head.",
  "linked-list-cycle-ii": "fast-slow: After they meet, reset one pointer to the head and move both by 1. They meet at the cycle start.",
  "rotate-list": "linked-list-pointer: Make the list circular, then cut at length − k % length.",
  "reorder-list": "fast-slow+linked-list-pointer: Find the middle, reverse the second half, interleave.",
  "sort-list": "recursion-divide+linked-list-pointer: Merge sort: split with fast/slow, sort both halves, merge.",
  "find-the-duplicate-number": "fast-slow: n+1 values in 1..n form a linked list with a cycle. The cycle entry is the duplicate.",
  "copy-list-with-random-pointer": "hash-lookup+linked-list-pointer: Map old node → new node, then wire next and random.",
  "lru-cache": "design-ds: Hash map + doubly linked list: O(1) lookup and O(1) move-to-front/evict.",
  "merge-k-sorted-lists": "k-way-merge: Min-heap of the k current heads, or merge pairs by divide and conquer.",
  "reverse-nodes-in-k-group": "linked-list-pointer: Check k nodes exist, reverse them, reconnect, repeat.",

  // ---- Stacks and queues ----
  "valid-parentheses": "stack-matching: Push openers. A closer must match the top.",
  "baseball-game": "stack-matching: Operations act on the most recent scores, a perfect stack.",
  "implement-queue-using-stacks": "design-ds: Two stacks: pour from input to output only when output is empty.",
  "implement-stack-using-queues": "design-ds: After each push, rotate the queue so the new item is at the front.",
  "number-of-recent-calls": "design-ds+sliding-window-variable: A queue of timestamps. Pop the ones older than 3000 ms.",
  "min-stack": "design-ds: Store (value, min so far) on each push.",
  "design-circular-queue": "design-ds: Fixed array with head and count, wrapping with modulo.",
  "evaluate-reverse-polish-notation": "stack-matching: Push numbers. On an operator pop two, compute, push the result.",
  "simplify-path": "stack-matching: Split by '/'. '..' pops, '.' and empty are skipped.",
  "decode-string": "stack-matching: Push (current string, repeat count) at '[', pop and repeat at ']'.",
  "next-greater-element-i": "monotonic-stack+hash-lookup: Next greater for nums2 with a stack, stored in a map.",
  "daily-temperatures": "monotonic-stack: Waiting for the next warmer day = next greater element, with index distances.",
  "next-greater-element-ii": "monotonic-stack: Circular array: loop 2n indices with i % n.",
  "online-stock-span": "monotonic-stack: Pop prices ≤ today and add their spans.",
  "asteroid-collision": "stack-matching: Only a right-moving asteroid followed by a left-moving one collide. Compare against the stack top.",
  "remove-k-digits": "monotonic-stack+greedy: Pop a larger previous digit while you still have removals left.",
  "car-fleet": "sort-then-scan+monotonic-stack: Sort by position. A car behind that arrives sooner merges into the fleet ahead.",
  "sum-of-subarray-minimums": "monotonic-stack: For each element, count subarrays where it is the minimum using previous-smaller and next-smaller.",
  "largest-rectangle-in-histogram": "monotonic-stack: Each bar extends to the previous and next smaller bar. Pop to settle the widths.",
  "maximal-rectangle": "monotonic-stack+dp-grid: Row by row build histogram heights, then largest-rectangle for each row.",
  "basic-calculator": "stack-matching: Keep a running result and sign. Push both at '(' and combine at ')'.",

  // ---- Backtracking ----
  "subsets": "backtracking-subsets: For each element: include it or not. Or use bitmasks 0..2ⁿ−1.",
  "letter-case-permutation": "backtracking-subsets: At each letter branch into lower and upper case.",
  "combinations": "backtracking-subsets: Choose in increasing order from start to avoid repeats; stop at size k.",
  "permutations": "backtracking-subsets: Used[] flags, or swap elements into position.",
  "subsets-ii": "backtracking-subsets: Sort, and skip a value equal to the previous one at the same depth.",
  "combination-sum": "backtracking-subsets: Reuse allowed, so recurse with the same index until the remaining sum drops below zero.",
  "combination-sum-ii": "backtracking-subsets: Each number once. Sort and skip duplicates at the same depth.",
  "combination-sum-iii": "backtracking-subsets: Numbers 1..9, exactly k of them, summing to n.",
  "permutations-ii": "backtracking-subsets: Sort, and skip a duplicate unless its previous twin is already used.",
  "letter-combinations-of-a-phone-number": "backtracking-subsets: One level per digit, branching over its letters.",
  "generate-parentheses": "backtracking-subsets: Add '(' while open < n and ')' while close < open.",
  "palindrome-partitioning": "backtracking-subsets+palindrome-expand: Cut at every index where the prefix is a palindrome, recurse on the rest.",
  "restore-ip-addresses": "backtracking-subsets: Four parts, each 1–3 digits, value ≤ 255, no leading zeros.",
  "word-search": "backtracking-subsets+grid-dfs-bfs: DFS from each cell, marking visited and unmarking on return.",
  "n-queens": "backtracking-subsets: Row by row, with sets for used columns and both diagonals.",
  "sudoku-solver": "backtracking-subsets: Fill the next empty cell with any digit allowed by row, column and box. Undo on failure.",

  // ---- Binary trees ----
  "binary-tree-inorder-traversal": "tree-dfs-recursion: Left, node, right. Iterative version uses a stack.",
  "binary-tree-preorder-traversal": "tree-dfs-recursion: Node, left, right.",
  "binary-tree-postorder-traversal": "tree-dfs-recursion: Left, right, node.",
  "maximum-depth-of-binary-tree": "tree-dfs-recursion: 1 + max(depth(left), depth(right)).",
  "minimum-depth-of-binary-tree": "tree-bfs-level: The first leaf found in level order is the shallowest.",
  "invert-binary-tree": "tree-dfs-recursion: Swap the children at every node.",
  "same-tree": "tree-dfs-recursion: Compare the values, then both subtrees in parallel.",
  "symmetric-tree": "tree-dfs-recursion: Compare left.left with right.right, and left.right with right.left.",
  "balanced-binary-tree": "tree-dfs-recursion: Return the height, or −1 if the subtree is unbalanced (bottom-up).",
  "diameter-of-binary-tree": "tree-dfs-recursion+dp-tree: At each node, longest path = leftHeight + rightHeight. Return only the height.",
  "path-sum": "tree-dfs-recursion: Pass the remaining sum down and check at leaves.",
  "binary-tree-level-order-traversal": "tree-bfs-level: Queue and process one level (queue size) per round.",
  "binary-tree-right-side-view": "tree-bfs-level: The last node of each level.",
  "binary-tree-zigzag-level-order-traversal": "tree-bfs-level: Level order, reversing every other level.",
  "subtree-of-another-tree": "tree-dfs-recursion: At each node run same-tree against the subtree.",
  "count-good-nodes-in-binary-tree": "tree-dfs-recursion: Pass the maximum on the path down. A node is good when it is ≥ that maximum.",
  "path-sum-ii": "tree-dfs-recursion+backtracking-subsets: Keep the current path, copy it at valid leaves, pop on return.",
  "lowest-common-ancestor-of-a-binary-tree": "lca: If both sides find a target, the current node is the LCA.",
  "construct-binary-tree-from-preorder-and-inorder-traversal": "tree-construct: Preorder gives the root, a map of inorder indices gives the left/right split.",
  "flatten-binary-tree-to-linked-list": "tree-dfs-recursion: Move the left subtree to the right, attaching the old right subtree at its tail.",
  "count-complete-tree-nodes": "binary-search-index+tree-dfs-recursion: If left and right heights match the subtree is perfect (2^h − 1), otherwise recurse.",
  "all-nodes-distance-k-in-binary-tree": "tree-to-graph+bfs-shortest: Add parent pointers, then BFS k levels out from the target.",
  "maximum-width-of-binary-tree": "tree-bfs-level: Number nodes like a heap (2i, 2i+1). Width = last − first + 1 per level.",
  "vertical-order-traversal-of-a-binary-tree": "tree-bfs-level+sort-then-scan: Record (column, row, value) per node, then sort.",
  "binary-tree-maximum-path-sum": "dp-tree: Return the best one-sided gain (ignore negatives). Update a global with left + node + right.",
  "serialize-and-deserialize-binary-tree": "tree-construct: Preorder with null markers, rebuilt with a queue or an index.",

  // ---- Binary search trees ----
  "search-in-a-binary-search-tree": "bst-inorder: Go left or right by comparing.",
  "insert-into-a-binary-search-tree": "bst-inorder: Walk down to the null spot and attach the new node.",
  "convert-sorted-array-to-binary-search-tree": "tree-construct: The middle element is the root. Recurse on both halves.",
  "minimum-absolute-difference-in-bst": "bst-inorder: Inorder is sorted, so compare neighbours only.",
  "validate-binary-search-tree": "bst-inorder: Pass (low, high) bounds down, or check that inorder is strictly increasing.",
  "kth-smallest-element-in-a-bst": "bst-inorder: Stop the inorder traversal at the k-th visit.",
  "lowest-common-ancestor-of-a-binary-search-tree": "lca+bst-inorder: The split point where p and q go to different sides.",
  "two-sum-iv-input-is-a-bst": "hash-lookup+bst-inorder: Two-sum with a set, or inorder to an array and two pointers.",
  "delete-node-in-a-bst": "bst-inorder: Leaf: remove. One child: replace. Two children: copy the inorder successor, then delete it.",
  "binary-search-tree-iterator": "bst-inorder+design-ds: Controlled inorder with a stack holding the left spine.",
  "construct-binary-search-tree-from-preorder-traversal": "tree-construct+bst-inorder: Recurse with an upper bound: take the next preorder value while it fits.",
  "recover-binary-search-tree": "bst-inorder: In the inorder sequence two values are swapped. Find the two dips and swap them back.",

  // ---- Heaps ----
  "last-stone-weight": "heap-topk: Repeatedly take the two largest, so a max-heap.",
  "kth-largest-element-in-a-stream": "heap-topk: Min-heap of size k. The root is the k-th largest.",
  "kth-largest-element-in-an-array": "heap-topk: Min-heap of size k, or quickselect for O(n) average.",
  "k-closest-points-to-origin": "heap-topk: Max-heap of size k by distance, or quickselect.",
  "top-k-frequent-words": "heap-topk+frequency-count: Count, then a heap ordered by (count, word) with the tie-break reversed.",
  "task-scheduler": "greedy+heap-topk: Handle the most frequent task first. The answer is bounded by (maxFreq−1)·(n+1) + ties.",
  "reorganize-string": "greedy+heap-topk: Always place the most frequent letter that isn't the previous one.",
  "design-twitter": "k-way-merge+design-ds: The feed is a merge of the recent tweets of everyone followed, using a heap.",
  "find-median-from-data-stream": "two-heaps: Max-heap for the lower half, min-heap for the upper half.",
  "ipo": "greedy+heap-topk: Sort by capital. Among affordable projects always take the best profit (max-heap).",
  "smallest-range-covering-elements-from-k-lists": "k-way-merge: Min-heap over one element per list, tracking the current max for the range.",

  // ---- Greedy ----
  "assign-cookies": "greedy+sort-then-scan: Sort both. Give each child the smallest cookie that satisfies them.",
  "lemonade-change": "greedy: Give back the largest bills first when you can.",
  "maximum-units-on-a-truck": "greedy+sort-then-scan: Sort boxes by units per box, take the best first.",
  "two-city-scheduling": "greedy+sort-then-scan: Sort by cost difference (a − b). Half go to each city.",
  "jump-game": "greedy: Track the farthest reachable index. Fail if you are beyond it.",
  "jump-game-ii": "greedy+bfs-shortest: Jump in layers: each layer is the range reachable with one more jump.",
  "gas-station": "greedy: If the total gas ≥ total cost a start exists. Restart after any negative running tank.",
  "hand-of-straights": "greedy+frequency-count: Start with the smallest card and build a consecutive run from it, using counts.",
  "partition-labels": "greedy+two-pointers-same: Last index of each letter. Close the partition when the pointer reaches the furthest last index.",
  "valid-parenthesis-string": "greedy: Keep a range [lo, hi] of possible open counts, where '*' widens it.",
  "merge-triplets-to-form-target-triplet": "greedy: Use only triplets that never exceed the target in any position, then check each target value is hit.",
  "candy": "greedy: Two passes: left to right for rising ratings, right to left for falling, take the max.",

  // ---- Intervals ----
  "merge-intervals": "intervals: Sort by start and extend the last interval while they overlap.",
  "insert-interval": "intervals: Add everything before, merge the overlapping run, then add everything after.",
  "non-overlapping-intervals": "intervals+greedy: Sort by end, keep the interval that finishes earliest. The rest are removals.",
  "minimum-number-of-arrows-to-burst-balloons": "intervals+greedy: Sort by end, shoot at the end of the first balloon, skip all it hits.",
  "interval-list-intersections": "two-pointers-same+intervals: Two pointers over both sorted lists. Overlap is [max starts, min ends], advance the one that ends first.",
  "car-pooling": "intervals+prefix-sum: Sweep line: +passengers at pickup, −passengers at drop-off.",
  "my-calendar-i": "intervals+ordered-set: A booking conflicts if it overlaps a neighbour. Check floor and ceiling in a sorted structure.",
  "minimum-interval-to-include-each-query": "intervals+heap-topk: Sort intervals and queries. Sweep and keep a min-heap by interval length.",

  // ---- Graphs: BFS and DFS ----
  "flood-fill": "grid-dfs-bfs: Fill the connected same-colour region.",
  "find-if-path-exists-in-graph": "graph-traversal: Build the graph, then DFS/BFS or union-find.",
  "number-of-islands": "grid-dfs-bfs: One flood fill per unvisited land cell is one island.",
  "max-area-of-island": "grid-dfs-bfs: Flood fill and return the area.",
  "island-perimeter": "matrix-traversal: Each land cell adds 4, minus 2 for every shared edge.",
  "keys-and-rooms": "graph-traversal: Reachability from room 0.",
  "number-of-provinces": "graph-traversal+union-find: Count the connected components of an adjacency matrix.",
  "clone-graph": "graph-traversal+hash-lookup: DFS/BFS with a map old → clone.",
  "rotting-oranges": "bfs-shortest: Multi-source BFS from all rotten oranges. The level count is the minutes.",
  "01-matrix": "bfs-shortest: Multi-source BFS from every 0 for the distance to the nearest 0.",
  "surrounded-regions": "grid-dfs-bfs: Flood from the border 'O's. The ones never reached get flipped.",
  "number-of-enclaves": "grid-dfs-bfs: Remove land connected to the border, then count what is left.",
  "pacific-atlantic-water-flow": "grid-dfs-bfs: Flood uphill from each ocean's border and intersect the two sets.",
  "is-graph-bipartite": "graph-coloring: BFS/DFS two-colouring. A same-colour neighbour is a failure.",
  "shortest-path-in-binary-matrix": "bfs-shortest: BFS with 8 directions. Level = path length.",
  "open-the-lock": "bfs-shortest: Each lock state is a node and each wheel turn is an edge. Avoid the dead ends.",
  "snakes-and-ladders": "bfs-shortest: Squares are nodes, a die roll gives up to 6 edges. Convert the zig-zag numbering carefully.",
  "word-ladder": "bfs-shortest: Words are nodes, one-letter changes are edges. Shortest transformation = BFS.",

  // ---- Graphs: advanced ----
  "course-schedule": "topo-sort: Prerequisites. A cycle means impossible.",
  "course-schedule-ii": "topo-sort: Output the Kahn's order.",
  "find-eventual-safe-states": "topo-sort: Reverse the edges and run Kahn's. Safe nodes are those that reach the sinks.",
  "redundant-connection": "union-find: The first edge whose ends already share a root closes the cycle.",
  "number-of-operations-to-make-network-connected": "union-find: Need components − 1 spare cables. Spare = edges that were redundant.",
  "accounts-merge": "union-find+hash-lookup: Union accounts that share an email, then group emails by root.",
  "most-stones-removed-with-same-row-or-column": "union-find: Stones sharing a row or column are in one component. Answer = stones − components.",
  "evaluate-division": "graph-traversal+union-find: Equations are weighted edges. Query by DFS/BFS multiplying weights, or weighted union-find.",
  "network-delay-time": "dijkstra: Time to reach the farthest node from the source with weighted edges.",
  "path-with-minimum-effort": "dijkstra+binary-search-answer: Minimise the maximum step on a path: Dijkstra with max instead of sum.",
  "cheapest-flights-within-k-stops": "bellman-ford-dp: At most k stops: k+1 rounds of relaxation using last round's copy.",
  "number-of-ways-to-arrive-at-destination": "dijkstra+dp-linear: Dijkstra, counting ways whenever a path ties the best distance.",
  "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance": "bellman-ford-dp: All-pairs shortest path on a small graph (Floyd-Warshall).",
  "min-cost-to-connect-all-points": "mst: Kruskal or Prim on Manhattan distances.",
  "swim-in-rising-water": "dijkstra+union-find: Minimise the maximum cell on the path: Dijkstra with max, or binary search + BFS.",
  "making-a-large-island": "grid-dfs-bfs+union-find: Label each island with its size, then try flipping each 0 and sum its distinct neighbouring islands.",
  "reconstruct-itinerary": "euler-path: Use every ticket once. Hierholzer with lexical order.",
  "critical-connections-in-a-network": "bridges-tarjan: Tarjan's low-link finds bridges.",
  "word-ladder-ii": "bfs-shortest+backtracking-subsets: BFS to get the distance layers, then DFS back to list every shortest path.",

  // ---- Dynamic programming: 1D ----
  "climbing-stairs": "dp-linear: ways(n) = ways(n−1) + ways(n−2).",
  "min-cost-climbing-stairs": "dp-linear: cost to reach i = min of the two previous steps' cost, plus the step cost.",
  "house-robber": "dp-linear: Rob this house (skip the previous) or skip it. dp[i] = max(dp[i−1], dp[i−2] + x).",
  "house-robber-ii": "dp-linear: Circular: run house-robber twice, excluding the first house, then excluding the last.",
  "delete-and-earn": "dp-linear: Bucket by value. Taking x forbids x−1 and x+1, which is house robber on the values.",
  "decode-ways": "dp-linear: dp[i] adds dp[i−1] if one digit is valid and dp[i−2] if the two-digit number is 10–26.",
  "coin-change": "dp-knapsack: dp[amount] = min coins. Unbounded knapsack. BFS by levels also works.",
  "perfect-squares": "dp-knapsack: Coin change where the coins are the perfect squares.",
  "maximum-product-subarray": "kadane: Track both max and min ending here, because a negative flips them.",
  "word-break": "dp-linear: dp[i] = some j < i has dp[j] true and s[j..i] in the dictionary.",
  "combination-sum-iv": "dp-knapsack: Count ordered sequences, so loop the target outside and the numbers inside.",
  "longest-increasing-subsequence": "dp-lis: O(n²) DP, or the tails[] array with binary search for O(n log n).",
  "partition-equal-subset-sum": "dp-knapsack: Can some subset reach sum/2? 0/1 knapsack (loop sums downward).",

  // ---- Dynamic programming: 2D and strings ----
  "unique-paths": "dp-grid+combinatorics-math: dp[r][c] = from above + from left. Or C(m+n−2, m−1).",
  "unique-paths-ii": "dp-grid: Same, with obstacle cells set to 0 ways.",
  "minimum-path-sum": "dp-grid: dp[r][c] = cost + min(above, left).",
  "triangle": "dp-grid: Bottom-up: each cell adds the smaller of the two cells below it.",
  "minimum-falling-path-sum": "dp-grid: Each cell adds the min of the three cells above it.",
  "maximal-square": "dp-grid: dp = 1 + min(left, up, diagonal) when the cell is 1.",
  "longest-common-subsequence": "dp-string-two: Match extends the diagonal. Otherwise the max of dropping a char from either.",
  "longest-palindromic-subsequence": "dp-string-two+palindrome-expand: LCS of the string and its reverse, or interval DP.",
  "palindromic-substrings": "palindrome-expand: Expand around 2n−1 centres and count each success.",
  "minimum-insertion-steps-to-make-a-string-palindrome": "dp-string-two: Answer = n − longest palindromic subsequence.",
  "edit-distance": "dp-string-two: Insert, delete or replace map to three neighbouring cells.",
  "coin-change-ii": "dp-knapsack: Count combinations, so loop coins outside and amounts inside.",
  "target-sum": "dp-knapsack: Reduce to a subset sum count: P − N = target, P + N = total.",
  "interleaving-string": "dp-string-two: dp[i][j] = s3[i+j] can be taken from s1[i−1] or s2[j−1].",
  "distinct-subsequences": "dp-string-two: On a character match, add (use it) + (skip it).",
  "shortest-common-supersequence": "dp-string-two: Build the LCS table, then walk back to merge the strings.",
  "cherry-pickup-ii": "dp-grid: Two robots move row by row, so the state is (row, col1, col2).",
  "wildcard-matching": "dp-string-two+greedy: dp[i][j] with '*' = match empty or consume one more character.",
  "regular-expression-matching": "dp-string-two: Like wildcard, but '*' applies to the previous character.",

  // ---- Dynamic programming: advanced ----
  "best-time-to-buy-and-sell-stock-with-cooldown": "dp-state-machine: States: holding, sold (cooldown), resting.",
  "best-time-to-buy-and-sell-stock-iii": "dp-state-machine: At most 2 transactions: four states, buy1, sell1, buy2, sell2.",
  "best-time-to-buy-and-sell-stock-iv": "dp-state-machine: Same with k transactions: a (day, transactions, holding) state.",
  "largest-divisible-subset": "dp-lis+sort-then-scan: Sort, then LIS where the relation is divisibility.",
  "longest-string-chain": "dp-lis+sort-then-scan: Sort by length. dp[word] = 1 + best of its one-letter-deleted predecessors.",
  "number-of-longest-increasing-subsequence": "dp-lis: Keep length and count per index.",
  "russian-doll-envelopes": "dp-lis+sort-then-scan: Sort by width ascending and height descending, then LIS on heights.",
  "partition-array-for-maximum-sum": "dp-linear: dp[i] = best over the last block length 1..k.",
  "palindrome-partitioning-ii": "dp-linear+palindrome-expand: Minimum cuts with a palindrome table (or expansion).",
  "minimum-cost-to-cut-a-stick": "dp-interval: Choose the last cut inside [l, r].",
  "burst-balloons": "dp-interval: Choose the LAST balloon to burst in [l, r] so the sides stay independent.",
  "house-robber-iii": "dp-tree: Return (rob this node, skip this node) from each subtree.",
  "partition-to-k-equal-sum-subsets": "dp-bitmask+backtracking-subsets: Mask of used numbers, filling one bucket at a time.",
  "shortest-path-visiting-all-nodes": "dp-bitmask+bfs-shortest: BFS over (node, visited mask).",
  "number-of-digit-one": "math-digits+recursion-divide: Count the contribution of each digit position (high, current, low).",

  // ---- Tries ----
  "implement-trie-prefix-tree": "trie: Insert, search and startsWith.",
  "design-add-and-search-words-data-structure": "trie+backtracking-subsets: Wildcard '.' branches into all children during DFS.",
  "replace-words": "trie: For each word walk the trie until a root ends.",
  "longest-word-in-dictionary": "trie: Walk only through nodes that are word-ends.",
  "search-suggestions-system": "trie+binary-search-index: Sorted words and a binary search per typed prefix, or a trie.",
  "maximum-xor-of-two-numbers-in-an-array": "trie+bit-manipulation: Bitwise trie: for each number go to the opposite bit when possible.",
  "word-search-ii": "trie+backtracking-subsets: Grid DFS guided by a trie of all words. Prune dead branches.",
  "palindrome-pairs": "trie+hash-lookup: For each word, split into prefix + suffix and look up whether the reverse of the other part exists.",

  // ---- Bit manipulation ----
  "number-of-1-bits": "bit-manipulation: n & (n−1) clears the lowest set bit. Count the steps.",
  "counting-bits": "bit-manipulation+dp-linear: bits[i] = bits[i >> 1] + (i & 1).",
  "reverse-bits": "bit-manipulation: Shift the result left and push in the lowest bit of n, 32 times.",
  "minimum-bit-flips-to-convert-number": "bit-manipulation: Count the set bits of a ^ b.",
  "single-number-ii": "bit-manipulation: Count each bit position modulo 3.",
  "single-number-iii": "xor-trick: XOR all, split by a set bit of the result, XOR each group.",
  "bitwise-and-of-numbers-range": "bit-manipulation: The answer is the common binary prefix of left and right.",
  "sum-of-two-integers": "bit-manipulation: sum = a ^ b, carry = (a & b) << 1. Repeat until no carry.",
  "divide-two-integers": "bit-manipulation: Subtract shifted copies of the divisor (doubling), handling overflow.",

  // ---- Advanced topics ----
  "range-sum-query-mutable": "segment-tree-bit: Range sum with point updates, so Fenwick or segment tree.",
  "count-of-smaller-numbers-after-self": "segment-tree-bit+merge-sort-count: Walk from the right, query a BIT on compressed values. Or count during merge sort.",
  "reverse-pairs": "merge-sort-count: Count cross pairs between sorted halves before merging.",
  "count-of-range-sum": "merge-sort-count+prefix-sum: Prefix sums, then count pairs inside [lower, upper] with merge sort or a BIT.",
  "the-skyline-problem": "intervals+heap-topk: Sweep line over building edges with a max-heap of heights.",
  "sliding-window-median": "two-heaps+ordered-set: Two heaps with lazy deletion, or a sorted container.",
  "shortest-palindrome": "string-matching: The longest palindromic prefix via KMP on s + '#' + reverse(s).",
  "repeated-string-match": "string-matching: Repeat A just enough times and search for B.",
  "longest-duplicate-substring": "string-matching+binary-search-answer: Binary search the length, check with a rolling hash.",
  "max-points-on-a-line": "hash-lookup+number-theory: For each point, count slopes (reduced by gcd) in a map.",
  "snapshot-array": "design-time-versioned: Per index store (snap_id, value) changes and binary search.",
  "stock-price-fluctuation": "design-ds+heap-topk: Map timestamp → price, plus two heaps with lazy deletion for min and max.",
  "lfu-cache": "design-ds: Map key → value and frequency, plus lists per frequency with a min-frequency pointer.",
  "all-oone-data-structure": "design-ds: Doubly linked list of count buckets plus a map key → bucket.",

  // ---- Final step: Google's most asked ----
  "number-of-visible-people-in-a-queue": "monotonic-stack: Process from the right with a decreasing stack and count the pops.",
  "first-missing-positive": "index-marking: Cyclic sort: put value v at index v−1, then the first mismatch is the answer.",
  "swap-adjacent-in-lr-string": "two-pointers-same: Skip the X's. The L/R sequence must match and L may only move left, R only right.",
  "longest-valid-parentheses": "stack-matching+dp-linear: Stack of indices of unmatched brackets, or dp on the closers.",
  "text-justification": "simulation: Greedily pack words per line, then distribute the spaces.",
  "reverse-linked-list-ii": "linked-list-pointer: Walk to position left−1, reverse the next stretch, reconnect.",
  "insert-delete-getrandom-o1": "design-ds+randomized: Array for random access plus a map value → index. Swap with the last to delete.",
  "range-module": "intervals+ordered-set: Keep a sorted list of disjoint ranges. Add and remove with merging.",
  "guess-the-word": "game-minimax-dp: Pick guesses that remove the most candidates (minimax on match counts).",
  "random-pick-with-weight": "randomized+prefix-sum: Prefix sums of the weights, random number, binary search for its bucket.",
  "frequency-of-the-most-frequent-element": "sliding-window-variable+sort-then-scan: Sort. Window is valid when (max × length − sum) ≤ k.",
  "find-all-duplicates-in-an-array": "index-marking: Values in 1..n. Mark seen with a sign flip, and a flipped slot means a duplicate.",
  "exclusive-time-of-functions": "stack-matching: A stack of running functions. On each event, charge the elapsed time to the top.",
  "rearrange-array-elements-by-sign": "two-pointers-same: Two write indices, positives at even slots and negatives at odd ones.",
  "separate-squares-i": "binary-search-answer: Search the horizontal line. Area below is monotonic in y.",
  "longest-non-decreasing-subarray-after-replacing-at-most-one-element": "dp-linear: Keep run lengths ending/starting at each index, and try bridging across one element.",
  "smallest-integer-divisible-by-k": "number-theory+hash-lookup: Track the remainder of 1, 11, 111… If a remainder repeats, there is no answer (pigeonhole).",
  "longest-balanced-subarray-ii": "segment-tree-bit+prefix-sum: Balance via prefix values and a range structure to find the earliest valid start.",
  "champagne-tower": "dp-grid: Simulate the overflow row by row: (poured − 1) / 2 flows to each child.",
  "minimum-number-of-increments-on-subarrays-to-form-a-target-array": "greedy: Add up every rise from one element to the next (the first element counts fully).",
  "maximum-product-of-splitted-binary-tree": "tree-dfs-recursion: Compute subtree sums, then maximise sub × (total − sub).",
  "predict-the-winner": "game-minimax-dp: dp[l][r] = best score difference for the player to move.",
  "smallest-subsequence-of-distinct-characters": "monotonic-stack+greedy: Pop a larger letter if it appears again later and the new letter is smaller.",
  "stone-game": "game-minimax-dp: Interval DP on score difference, though the first player always wins.",
  "swap-nodes-in-pairs": "linked-list-pointer: Dummy head and pairwise relinking.",
  "longest-increasing-path-in-a-matrix": "grid-dfs-bfs+dp-grid: DFS with memoisation. Strictly increasing means no cycles.",
  "peak-index-in-a-mountain-array": "binary-search-index: Follow the slope up or down.",
  "bus-routes": "bfs-shortest: BFS over routes, not stops. Map stop → routes.",
  "find-the-length-of-the-longest-common-prefix": "trie+hash-lookup: Store all prefixes of one array in a set/trie, then match the other array's prefixes.",
  "subarray-product-less-than-k": "sliding-window-variable: Positive numbers. Each right end adds (right − left + 1) subarrays.",
  "earliest-finish-time-for-land-and-water-rides-ii": "greedy+sort-then-scan: For each order, finish the first ride earliest then start the second at the best moment.",
  "stone-game-iii": "game-minimax-dp: dp[i] = best difference from i. Try taking 1, 2 or 3 piles.",
  "substring-with-concatenation-of-all-words": "sliding-window-fixed+frequency-count: Words have equal length. Slide by word length from each offset with a word-count map.",
  "path-sum-iii": "prefix-hash+tree-dfs-recursion: Prefix sums along the root path in a map. Backtrack the map on return.",
  "partition-array-into-two-arrays-to-minimize-sum-difference": "meet-in-middle: n ≤ 30 per half: enumerate subset sums per half by size and pair them with two pointers.",
  "convert-sorted-list-to-binary-search-tree": "tree-construct+fast-slow: The middle node (fast/slow) is the root. Recurse on the halves.",
  "maximum-good-subarray-sum": "prefix-hash: Map each value to its smallest prefix, then look up value ± k.",
  "maximum-score-from-grid-operations": "dp-grid+prefix-sum: Column prefix sums with a DP over how far each column is coloured.",
  "maximum-path-score-in-a-grid": "dp-grid: Path DP with an extra cost-budget dimension.",
  "find-the-prefix-common-array-of-two-arrays": "frequency-count: Track seen counts. A value is common once it has appeared in both.",
};
