// The DSA path: zero experience → Google. Each step builds on the one before it.
// why = what you learn and why it's here; milestone = what you can crack after finishing this step.
export const SEQUENCE = [
  { id: "basics", name: "Programming basics", topics: ["How to Approach a Problem"],
    why: "Loops, if-else and working with digits and characters. If you can solve these alone, your coding basics are ready.",
    problems: ["fizz-buzz","running-sum-of-1d-array","richest-customer-wealth","number-of-steps-to-reduce-a-number-to-zero","convert-the-temperature","smallest-even-multiple","count-odd-numbers-in-an-interval-range","subtract-the-product-and-sum-of-digits-of-an-integer","find-numbers-with-even-number-of-digits","count-the-digits-that-divide-a-number","difference-between-element-sum-and-digit-sum-of-an-array","sign-of-the-product-of-an-array","average-salary-excluding-the-minimum-and-maximum-salary","palindrome-number","reverse-integer","add-digits","jewels-and-stones","number-of-good-pairs","defanging-an-ip-address","to-lower-case","length-of-last-word","maximum-number-of-words-found-in-sentences"] },
  { id: "complexity-math", name: "Time complexity and maths", topics: ["Time Complexity", "Math", "Number Theory"],
    why: "Learn Big-O by feeling it: some of these time out if you loop too much. You also pick up the maths tricks interviews love (primes, GCD, digits).",
    problems: ["power-of-two","power-of-three","happy-number","ugly-number","self-dividing-numbers","perfect-number","count-of-matches-in-tournament","excel-sheet-column-number","excel-sheet-column-title","find-greatest-common-divisor-of-array","greatest-common-divisor-of-strings","plus-one","add-binary","factorial-trailing-zeroes","count-primes"] },
  { id: "arrays", name: "Arrays", topics: ["Array"],
    why: "Almost every interview question uses arrays. Start easy, then learn the classic medium ones like Kadane's algorithm and rotating a matrix.",
    problems: ["concatenation-of-array","build-array-from-permutation","shuffle-the-array","kids-with-the-greatest-number-of-candies","find-the-highest-altitude","max-consecutive-ones","third-maximum-number","check-if-array-is-sorted-and-rotated","missing-number","single-number","majority-element","find-all-numbers-disappeared-in-an-array","pascals-triangle","transpose-matrix","matrix-diagonal-sum","best-time-to-buy-and-sell-stock","best-time-to-buy-and-sell-stock-ii","rotate-array","maximum-subarray","product-of-array-except-self","majority-element-ii","next-permutation","set-matrix-zeroes","rotate-image","spiral-matrix"] },
  { id: "strings", name: "Strings", topics: ["String"],
    why: "Reversing, comparing and building strings. Interviewers use strings to check if your code is clean and handles edge cases.",
    problems: ["reverse-string","valid-palindrome","is-subsequence","longest-common-prefix","find-the-index-of-the-first-occurrence-in-a-string","largest-odd-number-in-string","remove-outermost-parentheses","maximum-nesting-depth-of-the-parentheses","rotate-string","roman-to-integer","isomorphic-strings","reverse-words-in-a-string","integer-to-roman","count-and-say","string-compression","zigzag-conversion","string-to-integer-atoi","longest-palindromic-substring","sum-of-beauty-of-all-substrings"] },
  { id: "hashing", name: "Hashing", topics: ["Hash Table", "Counting"],
    why: "The single most useful trick: remember what you've seen in a hash map, and O(n²) often becomes O(n).",
    problems: ["two-sum","contains-duplicate","valid-anagram","first-unique-character-in-a-string","ransom-note","word-pattern","intersection-of-two-arrays","intersection-of-two-arrays-ii","contains-duplicate-ii","longest-palindrome","group-anagrams","sort-characters-by-frequency","top-k-frequent-elements","valid-sudoku","longest-consecutive-sequence","4sum-ii","brick-wall","encode-and-decode-tinyurl"] },
  { id: "sorting", name: "Sorting", topics: ["Sorting", "Divide and Conquer"],
    why: "Write bubble, selection, insertion, merge and quick sort yourself in \"Sort an Array\". Then use sorting as a tool to make problems easy.",
    problems: ["sort-an-array","squares-of-a-sorted-array","sort-array-by-parity","relative-sort-array","merge-sorted-array","minimum-absolute-difference","maximum-product-of-three-numbers","sort-colors","h-index","largest-number"] },
  { id: "recursion", name: "Recursion", topics: ["Recursion"],
    why: "A function that calls itself. Take your time here: trees, graphs, backtracking and DP all build on this.",
    problems: ["fibonacci-number","n-th-tribonacci-number","powx-n","count-good-numbers","k-th-symbol-in-grammar","find-the-winner-of-the-circular-game","sum-of-all-subset-xor-totals","different-ways-to-add-parentheses"] },
  { id: "two-pointers", name: "Two pointers", topics: ["Two Pointers"],
    why: "Two indexes moving through the array turn many O(n²) pair problems into O(n).",
    problems: ["move-zeroes","remove-element","remove-duplicates-from-sorted-array","backspace-string-compare","valid-palindrome-ii","remove-duplicates-from-sorted-array-ii","two-sum-ii-input-array-is-sorted","3sum","3sum-closest","container-with-most-water","boats-to-save-people","4sum","trapping-rain-water"] },
  { id: "prefix", name: "Prefix sum", topics: ["Prefix Sum"],
    why: "Running totals answer any range-sum question instantly. Combined with a hash map, it counts subarrays in O(n).",
    problems: ["find-pivot-index","range-sum-query-immutable","range-sum-query-2d-immutable","product-of-the-last-k-numbers","subarray-sum-equals-k","binary-subarrays-with-sum","count-number-of-nice-subarrays","continuous-subarray-sum","subarray-sums-divisible-by-k","contiguous-array"] },
  { id: "sliding-window", name: "Sliding window", topics: ["Sliding Window"],
    why: "The go-to pattern for \"longest/shortest substring or subarray\" questions, which are very common in online tests.",
    milestone: "You can now clear most online coding tests (OAs), including service companies and many product companies.",
    problems: ["maximum-average-subarray-i","longest-substring-without-repeating-characters","maximum-points-you-can-obtain-from-cards","longest-repeating-character-replacement","permutation-in-string","find-all-anagrams-in-a-string","max-consecutive-ones-iii","fruit-into-baskets","minimum-size-subarray-sum","number-of-substrings-containing-all-three-characters","minimum-window-substring","sliding-window-maximum","subarrays-with-k-different-integers"] },
  { id: "binary-search", name: "Binary search", topics: ["Binary Search"],
    why: "First on sorted arrays, then the powerful version: binary search on the answer (\"what's the minimum speed that works?\").",
    problems: ["binary-search","search-insert-position","sqrtx","guess-number-higher-or-lower","first-bad-version","find-first-and-last-position-of-element-in-sorted-array","search-in-rotated-sorted-array","search-in-rotated-sorted-array-ii","find-minimum-in-rotated-sorted-array","find-peak-element","single-element-in-a-sorted-array","search-a-2d-matrix","search-a-2d-matrix-ii","find-k-closest-elements","kth-missing-positive-number","koko-eating-bananas","capacity-to-ship-packages-within-d-days","minimum-number-of-days-to-make-m-bouquets","find-the-smallest-divisor-given-a-threshold","time-based-key-value-store","split-array-largest-sum","median-of-two-sorted-arrays"] },
  { id: "linked-list", name: "Linked list", topics: ["Linked List", "Fast and Slow Pointers"],
    why: "Pointer handling. Draw every problem on paper first. Fast and slow pointers solve cycles and middles.",
    problems: ["reverse-linked-list","merge-two-sorted-lists","middle-of-the-linked-list","linked-list-cycle","remove-linked-list-elements","delete-node-in-a-linked-list","palindrome-linked-list","intersection-of-two-linked-lists","remove-nth-node-from-end-of-list","odd-even-linked-list","add-two-numbers","linked-list-cycle-ii","rotate-list","reorder-list","sort-list","find-the-duplicate-number","copy-list-with-random-pointer","lru-cache","merge-k-sorted-lists","reverse-nodes-in-k-group"] },
  { id: "stack", name: "Stacks and queues", topics: ["Stack", "Queue", "Monotonic Stack"],
    why: "Stacks match brackets and undo things. The monotonic stack solves \"next greater element\" problems in O(n).",
    problems: ["valid-parentheses","baseball-game","implement-queue-using-stacks","implement-stack-using-queues","number-of-recent-calls","min-stack","design-circular-queue","evaluate-reverse-polish-notation","simplify-path","decode-string","next-greater-element-i","daily-temperatures","next-greater-element-ii","online-stock-span","asteroid-collision","remove-k-digits","car-fleet","sum-of-subarray-minimums","largest-rectangle-in-histogram","maximal-rectangle","basic-calculator"] },
  { id: "backtracking", name: "Backtracking", topics: ["Backtracking", "Recursion"],
    why: "Try a choice, go deeper, undo it, try the next. Subsets, permutations and puzzles like N-Queens.",
    milestone: "Recursion is now second nature, so trees and graphs will feel much easier.",
    problems: ["subsets","letter-case-permutation","combinations","permutations","subsets-ii","combination-sum","combination-sum-ii","combination-sum-iii","permutations-ii","letter-combinations-of-a-phone-number","generate-parentheses","palindrome-partitioning","restore-ip-addresses","word-search","n-queens","sudoku-solver"] },
  { id: "trees", name: "Binary trees", topics: ["Binary Tree", "Depth-First Search", "Breadth-First Search"],
    why: "The most asked topic at Google and Amazon. Learn the 4 traversals, then \"ask your children, then decide\" recursion.",
    problems: ["binary-tree-inorder-traversal","binary-tree-preorder-traversal","binary-tree-postorder-traversal","maximum-depth-of-binary-tree","minimum-depth-of-binary-tree","invert-binary-tree","same-tree","symmetric-tree","balanced-binary-tree","diameter-of-binary-tree","path-sum","binary-tree-level-order-traversal","binary-tree-right-side-view","binary-tree-zigzag-level-order-traversal","subtree-of-another-tree","count-good-nodes-in-binary-tree","path-sum-ii","lowest-common-ancestor-of-a-binary-tree","construct-binary-tree-from-preorder-and-inorder-traversal","flatten-binary-tree-to-linked-list","count-complete-tree-nodes","all-nodes-distance-k-in-binary-tree","maximum-width-of-binary-tree","vertical-order-traversal-of-a-binary-tree","binary-tree-maximum-path-sum","serialize-and-deserialize-binary-tree"] },
  { id: "bst", name: "Binary search trees", topics: ["Binary Search Tree"],
    why: "Trees that stay sorted. Inorder traversal gives sorted order, which unlocks most of these.",
    problems: ["search-in-a-binary-search-tree","insert-into-a-binary-search-tree","convert-sorted-array-to-binary-search-tree","minimum-absolute-difference-in-bst","validate-binary-search-tree","kth-smallest-element-in-a-bst","lowest-common-ancestor-of-a-binary-search-tree","two-sum-iv-input-is-a-bst","delete-node-in-a-bst","binary-search-tree-iterator","construct-binary-search-tree-from-preorder-traversal","recover-binary-search-tree"] },
  { id: "heap", name: "Heaps", topics: ["Heap (Priority Queue)"],
    why: "Always get the smallest or largest item fast. Top-K, merging lists and running medians.",
    milestone: "This is the level asked in most SDE-1 interviews at product companies.",
    problems: ["last-stone-weight","kth-largest-element-in-a-stream","kth-largest-element-in-an-array","k-closest-points-to-origin","top-k-frequent-words","task-scheduler","reorganize-string","design-twitter","find-median-from-data-stream","ipo","smallest-range-covering-elements-from-k-lists"] },
  { id: "greedy", name: "Greedy", topics: ["Greedy"],
    why: "Take the best choice at each step. The skill is proving it works, or finding the counter-example that shows it doesn't.",
    problems: ["assign-cookies","lemonade-change","maximum-units-on-a-truck","two-city-scheduling","jump-game","jump-game-ii","gas-station","hand-of-straights","partition-labels","valid-parenthesis-string","merge-triplets-to-form-target-triplet","candy"] },
  { id: "intervals", name: "Intervals", topics: ["Intervals", "Sorting"],
    why: "Meetings, bookings and ranges. Sort by start (or end), then sweep through once.",
    problems: ["merge-intervals","insert-interval","non-overlapping-intervals","minimum-number-of-arrows-to-burst-balloons","interval-list-intersections","car-pooling","my-calendar-i","minimum-interval-to-include-each-query"] },
  { id: "graphs", name: "Graphs: BFS and DFS", topics: ["Graph Theory", "Breadth-First Search", "Depth-First Search"],
    why: "Islands, grids and networks. BFS gives shortest steps, DFS explores regions. Always keep a visited set.",
    problems: ["flood-fill","find-if-path-exists-in-graph","number-of-islands","max-area-of-island","island-perimeter","keys-and-rooms","number-of-provinces","clone-graph","rotting-oranges","01-matrix","surrounded-regions","number-of-enclaves","pacific-atlantic-water-flow","is-graph-bipartite","shortest-path-in-binary-matrix","open-the-lock","snakes-and-ladders","word-ladder"] },
  { id: "graphs-advanced", name: "Graphs: advanced", topics: ["Topological Sort", "Union-Find", "Shortest Path", "Minimum Spanning Tree"],
    why: "Topological sort, union-find, Dijkstra and MST. Google loves graphs, so being solid here puts you ahead of most candidates.",
    problems: ["course-schedule","course-schedule-ii","find-eventual-safe-states","redundant-connection","number-of-operations-to-make-network-connected","accounts-merge","most-stones-removed-with-same-row-or-column","evaluate-division","network-delay-time","path-with-minimum-effort","cheapest-flights-within-k-stops","number-of-ways-to-arrive-at-destination","find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance","min-cost-to-connect-all-points","swim-in-rising-water","making-a-large-island","reconstruct-itinerary","critical-connections-in-a-network","word-ladder-ii"] },
  { id: "dp-1d", name: "Dynamic programming: 1D", topics: ["Dynamic Programming", "Memoization"],
    why: "Start with recursion, add memoization, then turn it into a table. Go slowly: DP clicks after 20–30 problems.",
    problems: ["climbing-stairs","min-cost-climbing-stairs","house-robber","house-robber-ii","delete-and-earn","decode-ways","coin-change","perfect-squares","maximum-product-subarray","word-break","combination-sum-iv","longest-increasing-subsequence","partition-equal-subset-sum"] },
  { id: "dp-2d", name: "Dynamic programming: 2D and strings", topics: ["Dynamic Programming", "Knapsack"],
    why: "Grids, two strings and knapsack. Most of Google's DP questions are variations of these.",
    problems: ["unique-paths","unique-paths-ii","minimum-path-sum","triangle","minimum-falling-path-sum","maximal-square","longest-common-subsequence","longest-palindromic-subsequence","palindromic-substrings","minimum-insertion-steps-to-make-a-string-palindrome","edit-distance","coin-change-ii","target-sum","interleaving-string","distinct-subsequences","shortest-common-supersequence","cherry-pickup-ii","wildcard-matching","regular-expression-matching"] },
  { id: "dp-advanced", name: "Dynamic programming: advanced", topics: ["Dynamic Programming", "Bitmask"],
    why: "Stock problems, interval DP, LIS variants, DP on trees and bitmask DP. This is where hard interview questions live.",
    problems: ["best-time-to-buy-and-sell-stock-with-cooldown","best-time-to-buy-and-sell-stock-iii","best-time-to-buy-and-sell-stock-iv","largest-divisible-subset","longest-string-chain","number-of-longest-increasing-subsequence","russian-doll-envelopes","partition-array-for-maximum-sum","palindrome-partitioning-ii","minimum-cost-to-cut-a-stick","burst-balloons","house-robber-iii","partition-to-k-equal-sum-subsets","shortest-path-visiting-all-nodes","number-of-digit-one"] },
  { id: "trie", name: "Tries", topics: ["Trie"],
    why: "Trees of letters for prefix search and autocomplete, plus a bit trick for maximum XOR.",
    problems: ["implement-trie-prefix-tree","design-add-and-search-words-data-structure","replace-words","longest-word-in-dictionary","search-suggestions-system","maximum-xor-of-two-numbers-in-an-array","word-search-ii","palindrome-pairs"] },
  { id: "bits", name: "Bit manipulation", topics: ["Bit Manipulation"],
    why: "Short, clever tricks with AND, OR, XOR and shifts. Often asked as warm-up questions.",
    problems: ["number-of-1-bits","counting-bits","reverse-bits","minimum-bit-flips-to-convert-number","single-number-ii","single-number-iii","bitwise-and-of-numbers-range","sum-of-two-integers","divide-two-integers"] },
  { id: "advanced", name: "Advanced topics for Google", topics: ["Segment Tree", "String Matching", "Design", "Ordered Set"],
    why: "Segment trees, string matching, tricky design questions and hard classics. This is what separates a Google offer from a near miss.",
    milestone: "You've covered everything Google's coding rounds test. Finish with the final step below.",
    problems: ["range-sum-query-mutable","count-of-smaller-numbers-after-self","reverse-pairs","count-of-range-sum","the-skyline-problem","sliding-window-median","shortest-palindrome","repeated-string-match","longest-duplicate-substring","max-points-on-a-line","snapshot-array","stock-price-fluctuation","lfu-cache","all-oone-data-structure"] },
];
